# Generated by Django 5.2.7 on 2025-12-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledetails', '0003_alter_contactus_options_alter_projects_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_link',
            field=models.URLField(blank=True, help_text='Project link (if any)'),
        ),
    ]
